# Generated by Django 3.2.3 on 2021-06-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('COMIDA', 'Comida'), ('BEBIDA', 'Bebida'), ('SOBREMESA', 'Sobremesa'), ('CARNE', 'Carne'), ('VEGANO', 'Vegano'), ('VEGETARIANO', 'Vegetariano'), ('SALADA', 'Salada'), ('FRUTA', 'Fruta')], default='COMIDA', max_length=50)),
                ('urlField', models.URLField(max_length=300)),
                ('isVegeterian', models.BooleanField()),
                ('isVegan', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food')),
            ],
        ),
    ]
