# Generated by Django 3.2.3 on 2021-06-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='urlField',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('ALMOCO', 'ALMOCO'), ('JANTAR', 'JANTAR'), ('CAFE DA MANHA', 'CAFE DA MANHA')], max_length=50),
        ),
    ]
